In [1]:
import numpy as np
import pandas as pd

In [2]:
data = pd.read_csv("height-weight.csv")

In [4]:
data

,Weight,Height
0,45,120
1,58,135
2,48,123
3,60,145
4,70,160
5,78,162
6,80,163
7,90,175
8,95,182
9,78,170


Process of builiding ML Project

Data collection

Data understanding

Data cleaning 

Feature engineering

Model Building
* Variable declaration
* split the data
* call the model
* train the model
* evaluation
  
Model deployment

In [9]:
# Variable Declaration

x = data[["Height"]]  # input variable  # Always a data frame # 2 dimensional 
y = data["Weight"]  # output variable

In [10]:
y

0      45
1      58
2      48
3      60
4      70
5      78
6      80
7      90
8      95
9      78
10     82
11     95
12    105
13    100
14     85
15     78
16     50
17     65
18     76
19     87
20     45
21     56
22     72
Name: Weight, dtype: int64

In [14]:
# Split the data into train and test

In [12]:
# scikit learn: a library to build the ml model
!pip install scikit-learn


[notice] A new release of pip is available: 25.3 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip


   ---------------------------------------- 0.0/8.1 MB ? eta -:--:--
   -- ------------------------------------- 0.5/8.1 MB 5.4 MB/s eta 0:00:02
   ----- ---------------------------------- 1.0/8.1 MB 3.7 MB/s eta 0:00:02
   ------ --------------------------------- 1.3/8.1 MB 2.9 MB/s eta 0:00:03
   ------ --------------------------------- 1.3/8.1 MB 2.9 MB/s eta 0:00:03
   ------- -------------------------------- 1.6/8.1 MB 1.7 MB/s eta 0:00:04
   ----------- ---------------------------- 2.4/8.1 MB 1.9 MB/s eta 0:00:04
   -------------- ------------------------- 2.9/8.1 MB 2.0 MB/s eta 0:00:03
   --------------- ------------------------ 3.1/8.1 MB 1.9 MB/s eta 0:00:03
   ------------------ --------------------- 3.7/8.1 MB 2.0 MB/s eta 0:00:03
   -------------------- ------------------- 4.2/8.1 MB 2.1 MB/s eta 0:00:02
   ---------------------- ----------------- 4.5/8.1 MB 2.0 MB/s eta 0:00:02
   ---------------------- ----------------- 4.5/8.1 MB 2.0 MB/s eta 0:00:02
   ----------------

<function sklearn.model_selection._split.train_test_split(*arrays, test_size=None, train_size=None, random_state=None, shuffle=True, stratify=None)>

In [16]:
from sklearn.model_selection import train_test_split   
x_train, x_test, y_train, y_test = train_test_split(x,y, test_size = 0.30, random_state = 5)

In [17]:
x_train.shape

(16, 1)

In [18]:
x_test.shape

(7, 1)

In [19]:
y_train.shape

(16,)

In [20]:
y_test.shape

(7,)

In [ ]:
# Calling the model _ regression model 

In [21]:
from sklearn.linear_model import LinearRegression
model = LinearRegression()

In [22]:
model

,"fit_intercept fit_intercept: bool, default=TrueWhether to calculate the intercept for this model. If setto False, no intercept will be used in calculations(i.e. data is expected to be centered).",True
,"copy_X copy_X: bool, default=TrueIf True, X will be copied; else, it may be overwritten.",True
,"tol tol: float, default=1e-6The precision of the solution (`coef_`) is determined by `tol` whichspecifies a different convergence criterion for the `lsqr` solver.`tol` is set as `atol` and `btol` of :func:`scipy.sparse.linalg.lsqr` whenfitting on sparse training data. This parameter has no effect when fittingon dense data... versionadded:: 1.7",1e-06
,"n_jobs n_jobs: int, default=NoneThe number of jobs to use for the computation. This will only providespeedup in case of sufficiently large problems, that is if firstly`n_targets > 1` and secondly `X` is sparse or if `positive` is setto `True`. ``None`` means 1 unless in a:obj:`joblib.parallel_backend` context. ``-1`` means using allprocessors. See :term:`Glossary ` for more details.",None
,"positive positive: bool, default=FalseWhen set to ``True``, forces the coefficients to be positive. Thisoption is only supported for dense arrays.For a comparison between a linear regression model with positive constraintson the regression coefficients and a linear regression without such constraints,see :ref:`sphx_glr_auto_examples_linear_model_plot_nnls.py`... versionadded:: 0.24",False


In [23]:
# train the model

In [24]:
model.fit(x_train, y_train)

,"fit_intercept fit_intercept: bool, default=TrueWhether to calculate the intercept for this model. If setto False, no intercept will be used in calculations(i.e. data is expected to be centered).",True
,"copy_X copy_X: bool, default=TrueIf True, X will be copied; else, it may be overwritten.",True
,"tol tol: float, default=1e-6The precision of the solution (`coef_`) is determined by `tol` whichspecifies a different convergence criterion for the `lsqr` solver.`tol` is set as `atol` and `btol` of :func:`scipy.sparse.linalg.lsqr` whenfitting on sparse training data. This parameter has no effect when fittingon dense data... versionadded:: 1.7",1e-06
,"n_jobs n_jobs: int, default=NoneThe number of jobs to use for the computation. This will only providespeedup in case of sufficiently large problems, that is if firstly`n_targets > 1` and secondly `X` is sparse or if `positive` is setto `True`. ``None`` means 1 unless in a:obj:`joblib.parallel_backend` context. ``-1`` means using allprocessors. See :term:`Glossary ` for more details.",None
,"positive positive: bool, default=FalseWhen set to ``True``, forces the coefficients to be positive. Thisoption is only supported for dense arrays.For a comparison between a linear regression model with positive constraintson the regression coefficients and a linear regression without such constraints,see :ref:`sphx_glr_auto_examples_linear_model_plot_nnls.py`... versionadded:: 0.24",False


In [25]:
model.coef_

array([0.84830164])

In [26]:
model.intercept_

np.float64(-61.051989108362534)

In [28]:
y_pred = model.predict(x_test)

In [29]:
from sklearn.metrics import r2_score

In [30]:
print("Accracy is : ", np.round(r2_score(y_pred, y_test)*100,2) , "%")

Accracy is :  84.91 %


In [31]:
r2_score(y_pred, y_test)

0.8491307842639152

In [33]:
markds = pd.read_csv("Marksheet.csv")

In [34]:
markds

,Student_Name,Hindi,English,Maths,Science,SST,Total,Percentage
0,Arjun Singh,45,49.0,86,63,70,283.0,56.6
1,Mohit Yadav,46,53.0,78,64,68,290.0,58.0
2,Amit tiwari,47,48.0,67,67,56,263.0,52.6
3,Sumit Negi,48,49.0,89,62,67,276.0,55.2
4,Rohit Raj,49,48.5,95,45,78,274.5,54.9
5,Shivani Negi,50,48.0,97,78,89,320.0,64.0
6,Jyoti,51,47.5,72,87,90,333.5,66.7
7,Arpit,52,47.0,95,65,76,297.0,59.4
8,Surjan Singh,53,46.5,80,65,78,309.5,61.9
9,Duryodhan,54,46.0,91,45,65,288.0,57.6


In [46]:
x = pd.DataFrame(markds.iloc[:, 3])
y = pd.DataFrame(markds.iloc[:, -1])

In [47]:
x

,Maths
0,86
1,78
2,67
3,89
4,95
5,97
6,72
7,95
8,80
9,91


In [48]:
y

,Percentage
0,56.6
1,58.0
2,52.6
3,55.2
4,54.9
5,64.0
6,66.7
7,59.4
8,61.9
9,57.6


In [49]:
x_train, x_test, y_train, y_test = train_test_split(x,y, test_size = 0.30, random_state = 5)

In [50]:
model_2 = LinearRegression()

In [51]:
model_2

,"fit_intercept fit_intercept: bool, default=TrueWhether to calculate the intercept for this model. If setto False, no intercept will be used in calculations(i.e. data is expected to be centered).",True
,"copy_X copy_X: bool, default=TrueIf True, X will be copied; else, it may be overwritten.",True
,"tol tol: float, default=1e-6The precision of the solution (`coef_`) is determined by `tol` whichspecifies a different convergence criterion for the `lsqr` solver.`tol` is set as `atol` and `btol` of :func:`scipy.sparse.linalg.lsqr` whenfitting on sparse training data. This parameter has no effect when fittingon dense data... versionadded:: 1.7",1e-06
,"n_jobs n_jobs: int, default=NoneThe number of jobs to use for the computation. This will only providespeedup in case of sufficiently large problems, that is if firstly`n_targets > 1` and secondly `X` is sparse or if `positive` is setto `True`. ``None`` means 1 unless in a:obj:`joblib.parallel_backend` context. ``-1`` means using allprocessors. See :term:`Glossary ` for more details.",None
,"positive positive: bool, default=FalseWhen set to ``True``, forces the coefficients to be positive. Thisoption is only supported for dense arrays.For a comparison between a linear regression model with positive constraintson the regression coefficients and a linear regression without such constraints,see :ref:`sphx_glr_auto_examples_linear_model_plot_nnls.py`... versionadded:: 0.24",False


In [52]:
model_2.fit(x_train, y_train)

,"fit_intercept fit_intercept: bool, default=TrueWhether to calculate the intercept for this model. If setto False, no intercept will be used in calculations(i.e. data is expected to be centered).",True
,"copy_X copy_X: bool, default=TrueIf True, X will be copied; else, it may be overwritten.",True
,"tol tol: float, default=1e-6The precision of the solution (`coef_`) is determined by `tol` whichspecifies a different convergence criterion for the `lsqr` solver.`tol` is set as `atol` and `btol` of :func:`scipy.sparse.linalg.lsqr` whenfitting on sparse training data. This parameter has no effect when fittingon dense data... versionadded:: 1.7",1e-06
,"n_jobs n_jobs: int, default=NoneThe number of jobs to use for the computation. This will only providespeedup in case of sufficiently large problems, that is if firstly`n_targets > 1` and secondly `X` is sparse or if `positive` is setto `True`. ``None`` means 1 unless in a:obj:`joblib.parallel_backend` context. ``-1`` means using allprocessors. See :term:`Glossary ` for more details.",None
,"positive positive: bool, default=FalseWhen set to ``True``, forces the coefficients to be positive. Thisoption is only supported for dense arrays.For a comparison between a linear regression model with positive constraintson the regression coefficients and a linear regression without such constraints,see :ref:`sphx_glr_auto_examples_linear_model_plot_nnls.py`... versionadded:: 0.24",False


In [53]:
model_2.coef_

array([[-0.24421272]])

In [54]:
model_2.intercept_

array([81.64786236])

In [55]:
y_pred = model_2.predict(x_test)

In [56]:
print("Accracy is : ", np.round(r2_score(y_pred, y_test)*100,2) , "%")

Accracy is :  -449.65 %
